# Database Configuration
database:
  username: sa
  password: ''
  url: jdbc:h2:file:./data/boraestudar

# Discord OAuth Configuration
discord:
  client_id: 1237632955145257021
  client_secret: iV3vyZyUdz-7g-syVbFFqRCz5o3m3-O_
  redirect_uri: https://boraestudar.ngrok.dev/associate/callback
  token: MTIzNzYzMjk1NTE0NTI1NzAyMQ.G1F77C.1sr96uENcZgnptTyYbPPxJWUX5kVZNRcWh7np0
  guild_id: 1237585539314487476

# JWT Configuration
jwt:
  secret: =======================Tcc=BoraEstudar===========================
  expiration_time: 1440
  cookie_name: access_token

# Email Configuration
mail:
  host: smtp.gmail.com
  port: 587
  username: tccbackendapp@gmail.com
  password: "fulh rhcm dlqv tzny"

# Email Token Configuration
email_token:
  expiration_time_minutes: 60

# External Host Configuration
external:
  host: https://boraestudar.ngrok.dev/