# Database Configuration
database:
  username: sa
  password: ""
  url: jdbc:h2:file:./data/database_name

# Discord OAuth Configuration
discord:
  client_id: 12376198273145257021
  client_secret: your_discord_client_secret_here
  redirect_uri: https://my.redirect.url/associate/callback
  token: your_discord_bot_token_here
  guild_id: 123183745639314419286

# JWT Configuration
jwt:
  secret: my_jwt_secret_key_here
  expiration_time: 1440
  cookie_name: my_jwt_cookie_name_here

# Email Configuration
mail:
  host: smtp.gmail.com
  port: 587
  username: username@gmail.com
  password: your_email_password_here

# Email Token Configuration
email_token:
  expiration_time_minutes: 60

# External Host Configuration
external:
  host: https://my.external.host.com/

# H2 Database Configuration
h2:
  console:
    enabled: true
    path: /h2

# JPA Configuration
jpa:
  ddl_auto: create-drop
  show_sql: true
  format_sql: true
