spring:
  config:
    import: file:./config.yaml
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: ${discord.client_id}
            client-secret: ${discord.client_secret}
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            scope:
              - identify
            redirect-uri: ${discord.redirect_uri}
            #redirect-uri: "http://localhost:4200/associate/callback"
            clientName: FourScouts client
        provider:
          discord:
            authorizationUri: https://discord.com/oauth2/authorize?client_id=${discord.client_id}&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fdiscord%2Fusers&scope=identify&state=${idUsuario}
            tokenUri: https://discordapp.com/api/oauth2/token
            userInfoUri: https://discord.com/api/users/@me
            user-info-uri: username
  mail:
    host: ${mail.host}
    port: ${mail.port}
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    username: ${database.username:sa}
    password: ${database.password:}
    #    url: jdbc:h2:mem:testdb
    url: ${DB_URL:jdbc:h2:file:./data/boraestudar}
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}
      path: ${H2_CONSOLE_PATH:/h2}
  jpa:
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    sql:
      init:
        mode: always
        data-locations: classpath:/data.sql
security:
  jwt:
    secret: ${jwt.secret}
    expiration-time: ${jwt.expiration_time}
    jwtCookieName: ${jwt.cookie_name}
  email:
    token:
      expiration-time-minutes: ${email_token.expiration_time_minutes}
discord:
  token: ${discord.token}
  guildId: ${discord.guild_id}
external:
  host: ${external.host}
# host: http://localhost:4200/