spring:
  security:
    oauth2:
      client:
        registration:
          discord:
            client-id: ${DISCORD_CLIENT_ID}
            client-secret: ${DISCORD_CLIENT_SECRET}
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            scope:
              - identify
            redirect-uri: "http://localhost:8080/discord/users"
            clientName: FourScouts client
        provider:
          discord:
            authorizationUri: https://discord.com/oauth2/authorize?client_id=1237632955145257021&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fdiscord%2Fusers&scope=identify&state=${idUsuario}
            tokenUri: https://discordapp.com/api/oauth2/token
            userInfoUri: https://discord.com/api/users/@me
            user-info-uri: username

  datasource:
    name: boraestudar
    username: sa
    password: ''
    url: jdbc:h2:mem:testdb
    # url: jdbc:h2:~/data/testdb
    driverClassName: org.h2.Driver
  h2:
  console:
    enabled: true
    path: '/h2'
    port: 9092

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAILSERVICE_USERNAME}
    password: ${EMAILSERVICE_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  sql:
    init:
      data-locations: classpath:/data.sql

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-time: 1440
    jwtCookieName: 'access_token'
  email:
    token:
      expiration-time-minutes: 60

discord:
  token: ${DISCORD_TOKEN}
  guildId: 1237585539314487476

external:
  host: http://localhost:8080

# logging:
#   level:
#     org:
#       springframework: DEBUG
#         # security: DEBUG
#     com:
#       ufftcc: DEBUG